[package]
name = "sqlc-gen-core"
version = "0.0.0"
edition = "2021"
publish = false
description = "A crate for building sqlc plugins"

[dependencies]
prost = "0.14.1"

[build-dependencies]
prost-build = "0.14.1"
